version: "3"

services:
  client:
    container_name: client
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      VITE_APP_API_URL: http://localhost:8000/api
    restart: always
    networks:
      - react-app

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: "123456"
      DB_NAME: task-board
    depends_on:
      - postgres
    restart: always
    networks:
      - react-app

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: task-board
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    networks:
      - react-app

networks:
  react-app:
    driver: bridge

volumes:
  db-data:
